# Generated by Django 3.2.8 on 2022-12-14 01:36

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
